// Generated by scripts/sync-model-catalog.mjs.
export const MODEL_SOURCE = {
  "repository": "mukowaty/firefox-translations",
  "revision": "e43e74a227e023469fb1d1c0e560dd69c0408410",
  "baseUrl": "https://huggingface.co/mukowaty/firefox-translations/resolve/e43e74a227e023469fb1d1c0e560dd69c0408410"
};

export const MODEL_CATALOG = {
  "en-ja": {
    "sourceLanguage": "en",
    "targetLanguage": "ja",
    "version": "2.3",
    "files": {
      "lex": {
        "fileName": "lex.50.50.enja.s2t.bin",
        "location": "en-ja/lex.50.50.enja.s2t.bin.gz",
        "size": 3504993,
        "hash": "ff82cc7c26a318cd44c9d14baa1faaa4e983fb8d6d2248484510c05d6d0984fa",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.enja.intgemm.alphas.bin",
        "location": "en-ja/model.enja.intgemm.alphas.bin.gz",
        "size": 44089580,
        "hash": "73d0096cbb60f59ad87d91506ee8d618407bae4a52253396cea8759095310773",
        "compression": "gzip"
      },
      "srcvocab": {
        "fileName": "srcvocab.enja.spm",
        "location": "en-ja/srcvocab.enja.spm.gz",
        "size": 404352,
        "hash": "2886b3cf3efeb383215f8a4638dbf4f7cdfb24146721c337cc1e84a15d560401",
        "compression": "gzip"
      },
      "trgvocab": {
        "fileName": "trgvocab.enja.spm",
        "location": "en-ja/trgvocab.enja.spm.gz",
        "size": 431278,
        "hash": "5098ad2e028c34d7850cb836b812b510a18e7ac4dcdd87cdb5febc3369c3bf6f",
        "compression": "gzip"
      }
    }
  },
  "ja-en": {
    "sourceLanguage": "ja",
    "targetLanguage": "en",
    "version": "2.0",
    "files": {
      "lex": {
        "fileName": "lex.50.50.jaen.s2t.bin",
        "location": "ja-en/lex.50.50.jaen.s2t.bin.gz",
        "size": 4819431,
        "hash": "266617374a94add490a115f0594c0df18bbb696c94a056b396ddc53e5393dc7b",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.jaen.intgemm.alphas.bin",
        "location": "ja-en/model.jaen.intgemm.alphas.bin.gz",
        "size": 43084737,
        "hash": "483c9ad18e85fd0a8ccb15b305daf7929ee939abd606fdb55a4cacfa89a5be1f",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.jaen.spm",
        "location": "ja-en/vocab.jaen.spm.gz",
        "size": 746616,
        "hash": "339c8df4205f81e6a192ef2f7d1bbea928c183a2b07878723df895cf23daedac",
        "compression": "gzip"
      }
    }
  },
  "en-ko": {
    "sourceLanguage": "en",
    "targetLanguage": "ko",
    "version": "2.0",
    "files": {
      "lex": {
        "fileName": "lex.50.50.enko.s2t.bin",
        "location": "en-ko/lex.50.50.enko.s2t.bin.gz",
        "size": 3471311,
        "hash": "062ceb1b1173f81c5ece40fb45affb5b7cbd8eaaf295e5744647d0e94b04beef",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.enko.intgemm.alphas.bin",
        "location": "en-ko/model.enko.intgemm.alphas.bin.gz",
        "size": 33738001,
        "hash": "91ebb959edc11b6ff63d28b5e237106047673e5be2dfec99169352fd98f0f1be",
        "compression": "gzip"
      },
      "srcvocab": {
        "fileName": "srcvocab.enko.spm",
        "location": "en-ko/srcvocab.enko.spm.gz",
        "size": 402480,
        "hash": "2227e5841e4376a3de47010a22f77762d9259c7459959744f2505721b93134a3",
        "compression": "gzip"
      },
      "trgvocab": {
        "fileName": "trgvocab.enko.spm",
        "location": "en-ko/trgvocab.enko.spm.gz",
        "size": 412614,
        "hash": "676f821c4e0bab2f6b5af0e38fffdb7c053ad74ffa5a3e822e55fd2370af4008",
        "compression": "gzip"
      }
    }
  },
  "ko-en": {
    "sourceLanguage": "ko",
    "targetLanguage": "en",
    "version": "2.0",
    "files": {
      "lex": {
        "fileName": "lex.50.50.koen.s2t.bin",
        "location": "ko-en/lex.50.50.koen.s2t.bin.gz",
        "size": 4380580,
        "hash": "18b4ecaf51d3aaaf96468d3132f27b4fd93e14b61ea2dc1450142533855ae0e8",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.koen.intgemm.alphas.bin",
        "location": "ko-en/model.koen.intgemm.alphas.bin.gz",
        "size": 43140465,
        "hash": "ef93436a9acfcb21945379a08ca876b1a3bfa90d03d1040c28b3b03bf701a5bd",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.koen.spm",
        "location": "ko-en/vocab.koen.spm.gz",
        "size": 706864,
        "hash": "8b2222617bf1dff2f129dbd5f609e8576c3a57f6ea952111dfb2a6f2da848dd6",
        "compression": "gzip"
      }
    }
  },
  "en-zh-Hans": {
    "sourceLanguage": "en",
    "targetLanguage": "zh-Hans",
    "version": "2.2",
    "files": {
      "lex": {
        "fileName": "lex.50.50.enzh.s2t.bin",
        "location": "en-zh/lex.50.50.enzh.s2t.bin.gz",
        "size": 3537095,
        "hash": "a6a86815587ea3920b9e61f19b6b69d8507944ed4a15d277639619ce0a709bc8",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.enzh.intgemm.alphas.bin",
        "location": "en-zh/model.enzh.intgemm.alphas.bin.gz",
        "size": 30500315,
        "hash": "927de8ae55e97d9ebc29a051dfef37dd4310a1ee065b205f8e9cccfccb636a59",
        "compression": "gzip"
      },
      "srcvocab": {
        "fileName": "srcvocab.enzh.spm",
        "location": "en-zh/srcvocab.enzh.spm.gz",
        "size": 407784,
        "hash": "06a2e7c235ab702ab9018588048316e81546b5f24c02d293dab0b338549cfd01",
        "compression": "gzip"
      },
      "trgvocab": {
        "fileName": "trgvocab.enzh.spm",
        "location": "en-zh/trgvocab.enzh.spm.gz",
        "size": 425748,
        "hash": "6548dbda9f8636774f76a3d49b7a514f7d2084a0ced8883931aa07e736f6803b",
        "compression": "gzip"
      }
    }
  },
  "zh-Hans-en": {
    "sourceLanguage": "zh-Hans",
    "targetLanguage": "en",
    "version": "2.0",
    "files": {
      "lex": {
        "fileName": "lex.50.50.zhen.s2t.bin",
        "location": "zh-en/lex.50.50.zhen.s2t.bin.gz",
        "size": 4824122,
        "hash": "b1bef5f75f5068877afdb2db0eeb670129165976bfa2af4889928f59c264b7b9",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.zhen.intgemm.alphas.bin",
        "location": "zh-en/model.zhen.intgemm.alphas.bin.gz",
        "size": 44369188,
        "hash": "820f50dc36b1e25c97208fff0470bae7fda62bd6f371c4c4bf94947a9de58497",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.zhen.spm",
        "location": "zh-en/vocab.zhen.spm.gz",
        "size": 738862,
        "hash": "fd0cc08ddcbe480e3be06e6a86cb8aaf75f946263a5d9fc7d2773a197990cfb2",
        "compression": "gzip"
      }
    }
  },
  "en-zh-Hant": {
    "sourceLanguage": "en",
    "targetLanguage": "zh-Hant",
    "version": "2.0",
    "files": {
      "lex": {
        "fileName": "lex.50.50.enzh_hant.s2t.bin",
        "location": "en-zh_hant/lex.50.50.enzh_hant.s2t.bin.gz",
        "size": 2290215,
        "hash": "b254c97043a9ba5ff2791abac8b411dc024de6257576745a522ccc6c92421870",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.enzh_hant.intgemm.alphas.bin",
        "location": "en-zh_hant/model.enzh_hant.intgemm.alphas.bin.gz",
        "size": 33291007,
        "hash": "79cb710e5e66bb0490368bf158f42aff800a0f9ef2f6449d98dfb654f2d02669",
        "compression": "gzip"
      },
      "srcvocab": {
        "fileName": "srcvocab.enzh_hant.spm",
        "location": "en-zh_hant/srcvocab.enzh_hant.spm.gz",
        "size": 404976,
        "hash": "5ad55cf62d3e8b0a1cefacc0086b1ceb26d0df6415205714effa76bbb1a3063b",
        "compression": "gzip"
      },
      "trgvocab": {
        "fileName": "trgvocab.enzh_hant.spm",
        "location": "en-zh_hant/trgvocab.enzh_hant.spm.gz",
        "size": 416659,
        "hash": "324622c18601da5784569eeda74b77e5ae96b164657eb8029a9dabfdcd29803b",
        "compression": "gzip"
      }
    }
  },
  "zh-Hant-en": {
    "sourceLanguage": "zh-Hant",
    "targetLanguage": "en",
    "version": "2.0",
    "files": {
      "lex": {
        "fileName": "lex.50.50.zh_hanten.s2t.bin",
        "location": "zh_hant-en/lex.50.50.zh_hanten.s2t.bin.gz",
        "size": 3268812,
        "hash": "69046bfea1a70a556b5669be3c014958698683ef3c3f00b8dfd5c6b4e8f4f8ca",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.zh_hanten.intgemm.alphas.bin",
        "location": "zh_hant-en/model.zh_hanten.intgemm.alphas.bin.gz",
        "size": 33653648,
        "hash": "07af851b5a9160e84f3327e6f6151725e2712bed7b6b86edde5920fae107e55b",
        "compression": "gzip"
      },
      "srcvocab": {
        "fileName": "srcvocab.zh_hanten.spm",
        "location": "zh_hant-en/srcvocab.zh_hanten.spm.gz",
        "size": 423691,
        "hash": "e28a5484fce525e13a6cde4737b2fac08cb3c9cc60c13da9a6395c38833f7936",
        "compression": "gzip"
      },
      "trgvocab": {
        "fileName": "trgvocab.zh_hanten.spm",
        "location": "zh_hant-en/trgvocab.zh_hanten.spm.gz",
        "size": 408143,
        "hash": "071d675ee1a1b5faffbde94910814998f187df9717b007ae56d54d0a6ae791ac",
        "compression": "gzip"
      }
    }
  },
  "en-de": {
    "sourceLanguage": "en",
    "targetLanguage": "de",
    "version": "2.1",
    "files": {
      "lex": {
        "fileName": "lex.50.50.ende.s2t.bin",
        "location": "en-de/lex.50.50.ende.s2t.bin.gz",
        "size": 2314750,
        "hash": "0370d79cda6fed5dfa8f9b2a0009459bd2766893825bb5b8b5114169d18da6c4",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.ende.intgemm.alphas.bin",
        "location": "en-de/model.ende.intgemm.alphas.bin.gz",
        "size": 22992073,
        "hash": "e3a74458faba3ab2752ed8355c5e3979f13395279c8fc1bd3f54a3c2316e4975",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.ende.spm",
        "location": "en-de/vocab.ende.spm.gz",
        "size": 413879,
        "hash": "3b2ddbfac73f994f151a8994447d6b3d41ab0d3435da56f79c233f34d03e45c2",
        "compression": "gzip"
      }
    }
  },
  "de-en": {
    "sourceLanguage": "de",
    "targetLanguage": "en",
    "version": "2.0",
    "files": {
      "lex": {
        "fileName": "lex.50.50.deen.s2t.bin",
        "location": "de-en/lex.50.50.deen.s2t.bin.gz",
        "size": 2626658,
        "hash": "231e9caf62e0e867775d5f4c1f4cfae21e37c70d9bf2bd628fa468aeeb2ba869",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.deen.intgemm.alphas.bin",
        "location": "de-en/model.deen.intgemm.alphas.bin.gz",
        "size": 22403755,
        "hash": "38b245bcfc23f6d61fd98a187436ea1320a38f41896df411b103df3e83f51681",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.deen.spm",
        "location": "de-en/vocab.deen.spm.gz",
        "size": 413879,
        "hash": "88dcd7fdbf20dc60837ce837244d0d55b20f7079f2cbd2ba8e63530632028310",
        "compression": "gzip"
      }
    }
  },
  "en-es": {
    "sourceLanguage": "en",
    "targetLanguage": "es",
    "version": "2.1",
    "files": {
      "lex": {
        "fileName": "lex.50.50.enes.s2t.bin",
        "location": "en-es/lex.50.50.enes.s2t.bin.gz",
        "size": 2265250,
        "hash": "37a067966f28ff0ba430fddb7412bc5b07afa2cd2fd5a46d9ad74045a1a06380",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.enes.intgemm.alphas.bin",
        "location": "en-es/model.enes.intgemm.alphas.bin.gz",
        "size": 22698792,
        "hash": "fe4025fde24a4d5f80533cfb7acd53d0eb7f194dfc2d8f427f0d4563cfb6ac06",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.enes.spm",
        "location": "en-es/vocab.enes.spm.gz",
        "size": 409312,
        "hash": "ae2760c04bc6eb5362b16e5c2f145c376bb04bac421c33ba3c0766805e6f03b3",
        "compression": "gzip"
      }
    }
  },
  "es-en": {
    "sourceLanguage": "es",
    "targetLanguage": "en",
    "version": "2.0",
    "files": {
      "lex": {
        "fileName": "lex.50.50.esen.s2t.bin",
        "location": "es-en/lex.50.50.esen.s2t.bin.gz",
        "size": 2543246,
        "hash": "3d7856bfa3b12804bdc80f12fd828fd9062c462113ab73fbf87c5c3b68420813",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.esen.intgemm.alphas.bin",
        "location": "es-en/model.esen.intgemm.alphas.bin.gz",
        "size": 23288494,
        "hash": "54247f1e057180bca1d404dfd5c12836f65bc96cef7af98e59e55acb8bd093b1",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.esen.spm",
        "location": "es-en/vocab.esen.spm.gz",
        "size": 409312,
        "hash": "1658b529b8858cf2e1e8cef2c4e2d69654d77b5f714ac52205864b336dfeb3ee",
        "compression": "gzip"
      }
    }
  },
  "en-fr": {
    "sourceLanguage": "en",
    "targetLanguage": "fr",
    "version": "2.0",
    "files": {
      "lex": {
        "fileName": "lex.50.50.enfr.s2t.bin",
        "location": "en-fr/lex.50.50.enfr.s2t.bin.gz",
        "size": 2297334,
        "hash": "055987f0b585b61c4914fb4469e2392fda0b25d3f7784275974f920e7b631997",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.enfr.intgemm.alphas.bin",
        "location": "en-fr/model.enfr.intgemm.alphas.bin.gz",
        "size": 23045432,
        "hash": "22cdaf3dc9a1da6e5818b5576737182467f3cd97e6fd6f94e4273eb7b56d1e3f",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.enfr.spm",
        "location": "en-fr/vocab.enfr.spm.gz",
        "size": 409706,
        "hash": "5dcadaad8191fb4eb7677bce07098a20221dec95976a4db796f3a17cc82b4541",
        "compression": "gzip"
      }
    }
  },
  "fr-en": {
    "sourceLanguage": "fr",
    "targetLanguage": "en",
    "version": "2.0",
    "files": {
      "lex": {
        "fileName": "lex.50.50.fren.s2t.bin",
        "location": "fr-en/lex.50.50.fren.s2t.bin.gz",
        "size": 2649934,
        "hash": "395aa7767220e1bcfc085f2b2787ff98005d0075e55451f1e0832885e3d9642a",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.fren.intgemm.alphas.bin",
        "location": "fr-en/model.fren.intgemm.alphas.bin.gz",
        "size": 23175075,
        "hash": "06b1eeedd3944260d00a393d12ec7192490c5b7c930b97212faf4d5f5c90a2ee",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.fren.spm",
        "location": "fr-en/vocab.fren.spm.gz",
        "size": 409706,
        "hash": "8d15b219ffd32327b4cabf0d94a05a4fecb8923a4f386badbcbe5e86ede453a7",
        "compression": "gzip"
      }
    }
  },
  "en-pt": {
    "sourceLanguage": "en",
    "targetLanguage": "pt",
    "version": "2.1",
    "files": {
      "lex": {
        "fileName": "lex.50.50.enpt.s2t.bin",
        "location": "en-pt/lex.50.50.enpt.s2t.bin.gz",
        "size": 2117608,
        "hash": "265cff4ca31d3fc95628181de98cf668868b44903d69680284dc456aa4191545",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.enpt.intgemm.alphas.bin",
        "location": "en-pt/model.enpt.intgemm.alphas.bin.gz",
        "size": 23340019,
        "hash": "afb5ae08a2e40b622cd191584cca1df00721fea43de85cec74191fc180370f08",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.enpt.spm",
        "location": "en-pt/vocab.enpt.spm.gz",
        "size": 408686,
        "hash": "c2fbaf26f10563c77fa95cca465ad3666f61dd08bfaef5bb170abd582901f389",
        "compression": "gzip"
      }
    }
  },
  "pt-en": {
    "sourceLanguage": "pt",
    "targetLanguage": "en",
    "version": "2.0",
    "files": {
      "lex": {
        "fileName": "lex.50.50.pten.s2t.bin",
        "location": "pt-en/lex.50.50.pten.s2t.bin.gz",
        "size": 2487847,
        "hash": "b31185389533a97177cbf68ea756b78bfbaa24d31a865d72c6ed203fa414b2f6",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.pten.intgemm.alphas.bin",
        "location": "pt-en/model.pten.intgemm.alphas.bin.gz",
        "size": 22700409,
        "hash": "f2d2bb46d452cef561d35504bd198fa6c6ffc47187ee987406a2ac05d9c3935f",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.pten.spm",
        "location": "pt-en/vocab.pten.spm.gz",
        "size": 408686,
        "hash": "28c9eb4fb13f8eb661f6bb098560a1bf368d25ff890275028ea9d4f3f97b0416",
        "compression": "gzip"
      }
    }
  },
  "en-ru": {
    "sourceLanguage": "en",
    "targetLanguage": "ru",
    "version": "2.0",
    "files": {
      "lex": {
        "fileName": "lex.50.50.enru.s2t.bin",
        "location": "en-ru/lex.50.50.enru.s2t.bin.gz",
        "size": 1348215,
        "hash": "6f00f5d955b8b259cb4a78e5badf0958e5fef3ce153fd77a6dea0324518bb1b8",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.enru.intgemm.alphas.bin",
        "location": "en-ru/model.enru.intgemm.alphas.bin.gz",
        "size": 30698731,
        "hash": "3c6e3ffd275c96a220ae28ddb55b8c2b86b44ffecc1eeb6c8195c1536de4ac74",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.enru.spm",
        "location": "en-ru/vocab.enru.spm.gz",
        "size": 419005,
        "hash": "07ed9055319f2adc50a16bc7e636fe1547ab745eb986e40b6384956dc1fc6cfd",
        "compression": "gzip"
      }
    }
  },
  "ru-en": {
    "sourceLanguage": "ru",
    "targetLanguage": "en",
    "version": "1.1",
    "files": {
      "lex": {
        "fileName": "lex.50.50.ruen.s2t.bin",
        "location": "ru-en/lex.50.50.ruen.s2t.bin.gz",
        "size": 1962008,
        "hash": "6524f5c898f1fef52992bd2565a6d4acfafb6a4e8dcd6aef237bd888239418a0",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.ruen.intgemm.alphas.bin",
        "location": "ru-en/model.ruen.intgemm.alphas.bin.gz",
        "size": 12613599,
        "hash": "4a8a7b9b07c9e06a167ec5bf2542528817321516db4edf614fda45011fa8e5d1",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.ruen.spm",
        "location": "ru-en/vocab.ruen.spm.gz",
        "size": 419860,
        "hash": "cd70b828e99e4d0c79d48cd56d8579d656c87c1db20bf88883da3085dcbfef75",
        "compression": "gzip"
      }
    }
  },
  "en-it": {
    "sourceLanguage": "en",
    "targetLanguage": "it",
    "version": "2.1",
    "files": {
      "lex": {
        "fileName": "lex.50.50.enit.s2t.bin",
        "location": "en-it/lex.50.50.enit.s2t.bin.gz",
        "size": 2209348,
        "hash": "cd7ef06c0b872c15286a9796f105eb62693f14665490546ac70ce1c6c8f16d47",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.enit.intgemm.alphas.bin",
        "location": "en-it/model.enit.intgemm.alphas.bin.gz",
        "size": 23892889,
        "hash": "cfff470e9f29e27132723589a8bc985648f92773410e5f6fc43293d9e19f97f1",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.enit.spm",
        "location": "en-it/vocab.enit.spm.gz",
        "size": 407598,
        "hash": "8f99a6f493bf7e1a03fbba19928d7dc7bf9a1b7938238467f3e80a58c0d50485",
        "compression": "gzip"
      }
    }
  },
  "it-en": {
    "sourceLanguage": "it",
    "targetLanguage": "en",
    "version": "2.0",
    "files": {
      "lex": {
        "fileName": "lex.50.50.iten.s2t.bin",
        "location": "it-en/lex.50.50.iten.s2t.bin.gz",
        "size": 2532929,
        "hash": "504877085b31edfa3d31a1918a9a42c20fcbf85ff018caf46c54641db5538e62",
        "compression": "gzip"
      },
      "model": {
        "fileName": "model.iten.intgemm.alphas.bin",
        "location": "it-en/model.iten.intgemm.alphas.bin.gz",
        "size": 23301774,
        "hash": "0bc7221c2730723ac4477e8aa1d1d5bd0b9c3450cb8d006a6f86fe5da9129c27",
        "compression": "gzip"
      },
      "vocab": {
        "fileName": "vocab.iten.spm",
        "location": "it-en/vocab.iten.spm.gz",
        "size": 407598,
        "hash": "df05fae498f519a828eb388cd08ec1b7205a8bcaf2405a5feb9f5e30c49a0977",
        "compression": "gzip"
      }
    }
  }
};
