import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { MODEL_CATALOG } from "./model-catalog.mjs";
import { writeModelRegistry } from "./model-registry.mjs";
import { prepareRuntimeAssets } from "./runtime-assets.mjs";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const modelDirectory = path.join(projectRoot, "public", "models");
const attachmentRoot = "https://firefox-settings-attachments.cdn.mozilla.net/";

async function sha256File(filePath) {
  const bytes = await fs.readFile(filePath);
  return createHash("sha256").update(bytes).digest("hex");
}

async function isVerified(filePath, file) {
  try {
    const stats = await fs.stat(filePath);
    return stats.size === file.size && (await sha256File(filePath)) === file.hash;
  } catch (error) {
    if (error.code === "ENOENT") return false;
    throw error;
  }
}

async function ensureModelFile(model, file) {
  const pairName = `${model.sourceLanguage}-${model.targetLanguage}`;
  const pairDirectory = path.join(modelDirectory, pairName);
  const destination = path.join(pairDirectory, file.fileName);
  if (await isVerified(destination, file)) return;

  // Reuse files generated by the earlier Japanese-only build.
  const legacyDestination = path.join(modelDirectory, file.fileName);
  if (pairName === "en-ja" && (await isVerified(legacyDestination, file))) {
    await fs.mkdir(pairDirectory, { recursive: true });
    await fs.rename(legacyDestination, destination);
    return;
  }

  process.stdout.write(
    `Downloading ${pairName}/${file.fileName} (${Math.round(file.size / 1024 / 1024)} MB)...\n`,
  );
  const response = await fetch(new URL(file.location, attachmentRoot), {
    credentials: "omit",
  });
  if (!response.ok) {
    throw new Error(`Failed to download ${file.fileName}: HTTP ${response.status}`);
  }
  const bytes = Buffer.from(await response.arrayBuffer());
  const actualHash = createHash("sha256").update(bytes).digest("hex");
  if (bytes.length !== file.size || actualHash !== file.hash) {
    throw new Error(`Integrity check failed for ${file.fileName}`);
  }
  await fs.mkdir(pairDirectory, { recursive: true });
  await fs.writeFile(destination, bytes);
}

await fs.mkdir(modelDirectory, { recursive: true });
for (const model of Object.values(MODEL_CATALOG)) {
  for (const file of Object.values(model.files)) {
    await ensureModelFile(model, file);
  }
}

await writeModelRegistry(
  path.join(projectRoot, "public", "model-registry.json"),
  "/models",
);
await prepareRuntimeAssets(projectRoot);
